trigger:
- main

pool:
  name: 'AgentDevops'  # Remplacez par le nom de votre pool d'agents local

variables:
  phpVersion: 8.3.7
  system.debug: true

steps:
- checkout: self
  fetchDepth: 0

# Set PHP version
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

# Ensure Composer is installed
- script: |
    if ! [ -x "$(command -v composer)" ]; then
      curl -sS https://getcomposer.org/installer | php
      sudo mv composer.phar /usr/local/bin/composer
    fi
    composer -v
  displayName: 'Install Composer if not available'

# Install PHP dependencies
- script: composer install --no-interaction --prefer-dist
  displayName: 'Install PHP Dependencies with Composer'

# Run tests with PHPUnit
- script: vendor/bin/phpunit
  displayName: 'Run PHPUnit Tests'
