trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 8.1

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'Install dependencies'

- script: |
    ./vendor/bin/phpunit --configuration phpunit.xml
  displayName: 'Run PHP Unit Tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'path/to/build'
    ArtifactName: 'php_project_artifacts'
    publishLocation: 'Container'
